import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { Providers } from "./providers";
import AppNavbar from "~/components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`font-sans ${inter.variable} dark`}>
        <Providers>
          <div className="flex min-h-screen flex-col">
            <AppNavbar />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
